project_name: k8s-image-auditor

# 0. PRE-HOOKS: Setup the "Fake" Go Environment
before:
  hooks:
    # 1. Create the dummy Go file
    - sh -c 'echo "package main; func main() {}" > main.go'
    # 2. Initialize a dummy Go module (Fixes "cannot find main module" error)
    - sh -c 'go mod init k8s-image-auditor || true'

# 1. BUILD: The "Fake" Build
builds:
  - id: k8s-image-auditor
    
    # Force creation of artifacts for these OS/Arch combos
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    main: .
    binary: k8s-image-auditor

    # Disable CGO for pure static builds (faster/safer for dummy builds)
    env:
      - CGO_ENABLED=0

    # THE MAGIC: Overwrite the compiled binary with our Bash script
    hooks:
      post:
        - cp k8s-image-auditor.sh {{ .Path }}
        - sed -i 's/VERSION="0.0.0-dev"/VERSION="{{ .Version }}"/' {{ .Path }}

# 2. ARCHIVES: Package the script + docs
archives:
  - id: default
    format: tar.gz
    # Standard naming convention for Homebrew
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: Makefile
      - src: k8s-image-auditor.1.md
      - src: completions.bash
      - src: _k8s-image-auditor

checksum:
  name_template: 'checksums.txt'

# 3. HOMEBREW: Update the Tap
brews:
  - name: k8s-image-auditor
    repository:
      owner: PraveenPrabhuT
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN }}"
    
    # FIX: Explicitly target the Formula folder to overwrite the correct file
    directory: Formula

    description: "Audits container images for architecture compatibility"
    homepage: "https://github.com/PraveenPrabhuT/k8s-image-auditor"
    license: "MIT"

    # Runtime Dependencies
    dependencies:
      - name: jq
      - name: kubernetes-cli
      - name: skopeo
      - name: awscli
      - name: pandoc

    install: |
      system "make", "install", "PREFIX=#{prefix}"
    
    test: |
      assert_match "Usage:", shell_output("#{bin}/k8s-image-auditor -h")